jobs: 
  - 
    job: Windows
    pool: 
      vmImage: vs2017-win2016
    steps: 
      - 
        checkout: self
        submodules: recursive
      - 
        script: |
            curl -sSf -o rustup-init.exe https://win.rustup.rs
            rustup-init.exe -y --default-toolchain stable
            echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%/.cargo/bin"
        displayName: "Install Dependencies"
      - 
        script: |
            set SOURCEMOD=deps/sourcemod
            set MMSOURCE=deps/mmsource
            set HL2SDKCSGO=deps/hl2sdk-csgo
            rustup target add i686-pc-windows-msvc
            cargo build --target i686-pc-windows-msvc --release
        displayName: Build
  - 
    job: Linux
    pool: 
      vmImage: ubuntu-16.04
    steps: 
      - 
        checkout: self
        submodules: recursive
      - 
        script: |
            sudo apt-get install gcc-multilib g++-multilib
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: "Install Dependencies"
      - 
        script: |
            export SOURCEMOD="deps/sourcemod"
            export MMSOURCE="deps/mmsource"
            export HL2SDKCSGO="deps/hl2sdk-csgo"
            rustup target add i686-unknown-linux-gnu
            cargo build --target i686-unknown-linux-gnu --release
        displayName: Build
