jobs: 
  - 
    job: Windows
    pool: 
      name: Builders
      demands:
      - Agent.OS -equals Windows_NT
    steps: 
      - 
        checkout: self
        submodules: recursive
      - 
        script: |
            curl -sSf -o rustup-init.exe https://win.rustup.rs
            rustup-init.exe -y --default-toolchain stable
            echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%/.cargo/bin"
        displayName: "Install Dependencies"
      - 
        script: |
            set SOURCEMOD=deps/sourcemod
            set MMSOURCE=deps/mmsource
            set HL2SDKCSGO=deps/hl2sdk-csgo
            rustup target add i686-pc-windows-msvc
            cargo build --target i686-pc-windows-msvc --release
        displayName: Build
      - 
        task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "target/i686-pc-windows-msvc/release"
          artifactName: "SM-Ext-Audio_windows"
          publishLocation: "Container"
  - 
    job: Linux
    pool: 
      name: Builders
      demands:
      - Agent.OS -equals Linux
    steps: 
      - 
        checkout: self
        submodules: recursive
      - 
        script: |
            sudo apt-get install gcc-multilib g++-multilib
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
            echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: "Install Dependencies"
      - 
        script: |
            export SOURCEMOD="deps/sourcemod"
            export MMSOURCE="deps/mmsource"
            export HL2SDKCSGO="deps/hl2sdk-csgo"
            rustup target add i686-unknown-linux-gnu
            cargo build --target i686-unknown-linux-gnu --release
        displayName: Build
      - 
        task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "target/i686-unknown-linux-gnu/release"
          artifactName: "SM-Ext-Audio_linux"
          publishLocation: "Container"
