jobs: 
  - 
    job: Windows
    pool: 
      name: Builders
      demands:
      - Agent.OS -equals Windows_NT
    steps: 
      - 
        checkout: self
        submodules: recursive
        displayName: Git Clone Recursively
      - 
        script: |
            set SOURCEMOD=deps/sourcemod
            set MMSOURCE=deps/mmsource
            set HL2SDKCSGO=deps/hl2sdk-csgo
            rustup target add i686-pc-windows-msvc
            cargo build --target i686-pc-windows-msvc --release
        displayName: Build
      - 
        task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "target/i686-pc-windows-msvc/release"
          artifactName: "SM-Ext-Audio_windows"
          publishLocation: "Container"
          displayName: Publish Artifacts
  - 
    job: Linux
    pool: 
      name: Builders
      demands:
      - Agent.OS -equals Linux
    steps: 
      - 
        checkout: self
        submodules: recursive
        displayName: Git Clone Recursively
      - 
        script: |
            export SOURCEMOD="deps/sourcemod"
            export MMSOURCE="deps/mmsource"
            export HL2SDKCSGO="deps/hl2sdk-csgo"
            rustup target add i686-unknown-linux-gnu
            cargo build --target i686-unknown-linux-gnu --release
        displayName: Build
      - 
        task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: "target/i686-unknown-linux-gnu/release"
          artifactName: "SM-Ext-Audio_linux"
          publishLocation: "Container"
          displayName: Publish Artifacts
